---
- name: Add the flathub flatpak remote to the system installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install faltpak packages
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    remote: flathub
  with_items: "{{ software_desktop_package_flatpak_packages }}"
