---

- name: Debian based distribution
  block:

  - name: install dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - python3-urllib3

  - name: Download the 1Password key
    ansible.builtin.get_url:
      url: "https://downloads.1password.com/linux/keys/1password.asc"
      dest: /tmp/1password.asc
  
  - name: Add the key for the 1Password apt repository
    ansible.builtin.command:
      cmd: "gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg /tmp/1password.asc"
      creates: /usr/share/keyrings/1password-archive-keyring.gpg

  - name: Add the 1Password apt repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
      state: present
      filename: 1password

  - name: Add the debsig-verify policy directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    loop:
      - /etc/debsig/policies/AC2D62742012EA22/
      - /usr/share/debsig/keyrings/AC2D62742012EA22/

  - name: Add the debsig-verify policy
    ansible.builtin.get_url:
      url: "https://downloads.1password.com/linux/debian/debsig/1password.pol"
      dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol

  - name: Add the key for the 1Password debsig-verify policy
    ansible.builtin.command:
      cmd: "gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg /tmp/1password.asc"
      creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

  - name: Add the key for the Google apt repository
    ansible.builtin.apt_key:
      url: "https://dl.google.com/linux/linux_signing_key.pub"
      state: present
      keyring: /etc/apt/trusted.gpg.d/google.gpg

  - name: Add the Google Chrome apt repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/google.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
      state: present
      filename: google-chrome

  when: ansible_os_family == 'Debian'

- name: RedHat based distributions
  block:

  - name: ensure google chrome repo is present
    copy:
      src: 'google-chrome.repo'
      dest: '/etc/yum.repos.d/'
      owner: 'root'
      group: 'root'
      mode: '0644'

  when: ansible_os_family == 'RedHat'
