---
- name: enable classic snap support
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link
  when: "ansible_facts['distribution'] == 'Fedora'"

- name: install Slack
  community.general.snap:
    name: slack
    classic: yes

- name: install Spotify
  community.general.snap:
    name: spotify

- name: install Todoist
  community.general.snap:
    name: todoist
