---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: desktop-fedora34
    image: "geerlingguy/docker-fedora34-ansible:latest"
    pre_build_image: true
  - name: desktop-fedora35
    image: "fedora:35"
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
